language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist --dev

script: "vendor/bin/phpunit --bootstrap=tests/bootstrap.php tests/"
